"""empty message

Revision ID: 18fa6be6d802
Revises: 36214d43d386
Create Date: 2017-10-22 22:17:05.719569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18fa6be6d802'
down_revision = '36214d43d386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paraphrase', 'text')
    op.drop_column('sample', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('text', mysql.TEXT(collation=u'utf8mb4_unicode_ci'), nullable=True))
    op.add_column('paraphrase', sa.Column('text', mysql.TEXT(collation=u'utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###
