"""empty message

Revision ID: 1b9b8d23e38b
Revises: 29f3b895411a
Create Date: 2017-11-16 18:46:24.330203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9b8d23e38b'
down_revision = '29f3b895411a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'id')
    # ### end Alembic commands ###
