"""empty message

Revision ID: 42bcadabe3cc
Revises: 6daba4c622e3
Create Date: 2017-10-29 20:32:41.207297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bcadabe3cc'
down_revision = '6daba4c622e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('task_id', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'task_id')
    # ### end Alembic commands ###
