"""empty message

Revision ID: 6daba4c622e3
Revises: 75f2f6f99897
Create Date: 2017-10-28 18:11:23.711350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6daba4c622e3'
down_revision = '75f2f6f99897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('china_name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'china_name')
    # ### end Alembic commands ###
