"""empty message

Revision ID: bac2aaefebb0
Revises: 1b9b8d23e38b
Create Date: 2017-11-16 18:59:31.377198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bac2aaefebb0'
down_revision = '1b9b8d23e38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('name', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('value', mysql.TEXT(collation=u'utf8mb4_unicode_ci'), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_collate=u'utf8mb4_unicode_ci',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
