"""empty message

Revision ID: c05d2dbca672
Revises: c45c0588b210
Create Date: 2017-10-28 13:02:05.425433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05d2dbca672'
down_revision = 'c45c0588b210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('chose_dictionary', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'chose_dictionary')
    # ### end Alembic commands ###
