"""empty message

Revision ID: c45c0588b210
Revises: 18fa6be6d802
Create Date: 2017-10-28 11:31:14.847343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45c0588b210'
down_revision = '18fa6be6d802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pos', sa.Column('tag', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pos', 'tag')
    # ### end Alembic commands ###
