"""empty message

Revision ID: de0fba40d62d
Revises: f06c46b49f9d
Create Date: 2017-10-30 20:41:25.931730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0fba40d62d'
down_revision = 'f06c46b49f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('task_log_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'task_log_id')
    # ### end Alembic commands ###
