"""empty message

Revision ID: f06c46b49f9d
Revises: 42bcadabe3cc
Create Date: 2017-10-30 17:47:20.112306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06c46b49f9d'
down_revision = '42bcadabe3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_check_log_checker_id'), 'check_log', ['checker_id'], unique=False)
    op.create_index(op.f('ix_check_log_task_log_id'), 'check_log', ['task_log_id'], unique=False)
    op.create_index(op.f('ix_paraphrase_dictionary_id'), 'paraphrase', ['dictionary_id'], unique=False)
    op.create_index(op.f('ix_paraphrase_pos_id'), 'paraphrase', ['pos_id'], unique=False)
    op.create_index(op.f('ix_paraphrase_source_id'), 'paraphrase', ['source_id'], unique=False)
    op.create_index(op.f('ix_sample_paraphrase_id'), 'sample', ['paraphrase_id'], unique=False)
    op.create_index(op.f('ix_task_log_task_id'), 'task_log', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_log_user_id'), 'task_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_log_user_id'), table_name='task_log')
    op.drop_index(op.f('ix_task_log_task_id'), table_name='task_log')
    op.drop_index(op.f('ix_sample_paraphrase_id'), table_name='sample')
    op.drop_index(op.f('ix_paraphrase_source_id'), table_name='paraphrase')
    op.drop_index(op.f('ix_paraphrase_pos_id'), table_name='paraphrase')
    op.drop_index(op.f('ix_paraphrase_dictionary_id'), table_name='paraphrase')
    op.drop_index(op.f('ix_check_log_task_log_id'), table_name='check_log')
    op.drop_index(op.f('ix_check_log_checker_id'), table_name='check_log')
    # ### end Alembic commands ###
